# Generated by Django 2.2.7 on 2020-01-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
